
CREATE TABLE "employee_final" (
    "Employee_No" INT   NOT NULL,
    "Position" VARCHAR   NOT NULL,
    "Department" VARCHAR   NOT NULL,
    "PayRate" MONEY   NOT NULL,
    "FLSAStatus" VARCHAR   NOT NULL,
    "HireDate" DATE   NOT NULL,
    "TermDate" DATE,
    "TermReason" VARCHAR  NOT NULL,
    "EmployStatus" VARCHAR   NOT NULL,
    "ManagerName" VARCHAR   NOT NULL,
    "Performance_Score" VARCHAR   NOT NULL,
    "DaysEmployed" INT   NOT NULL,
    "PositionID" INT   NOT NULL,
    "EngagementSurvey" FLOAT   NOT NULL,
    "EmpSatisfaction" INT   NOT NULL,
    "Source" VARCHAR   NOT NULL,
    "Post_Education" VARCHAR   NOT NULL,
    "School" VARCHAR   NOT NULL,
    "CitizenDesc" VARCHAR   NOT NULL,
    "Hispanic/Latino" VARCHAR   NOT NULL,
    "Race/Desc" VARCHAR   NOT NULL,
    "State" VARCHAR   NOT NULL,
    "ZIP" INT   NOT NULL,
    "DOB" DATE   NOT NULL,
    "Age" INT   NOT NULL,
    "Sex" VARCHAR   NOT NULL,
    "MaritalDesc" VARCHAR   NOT NULL
);